FROM diejmon/swift_on_arm_dockerfiles:5_0
LABEL maintainer="Alexander Belyavskiy"
LABEL Description="Ubuntu_18.04 ARM64 Swift5_0 with dependencies for Kitura"

RUN apt-get install openssl libssl-dev libbsd0 libcurl4-openssl-dev -y